#!/usr/bin/env bash
# Regenerates internal/service/vk_postprocess_spv.h from
# internal/service/shaders/vk_postprocess.comp.
#
# Run this after editing the shader source. Requires glslc (ships with the
# Android NDK under shader-tools/<host>/glslc, or the Vulkan SDK).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLIENT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
SRC="$CLIENT_DIR/internal/service/shaders/vk_postprocess.comp"
OUT_HEADER="$CLIENT_DIR/internal/service/vk_postprocess_spv.h"

GLSLC="${GLSLC:-}"
if [ -z "$GLSLC" ]; then
    if command -v glslc >/dev/null 2>&1; then
        GLSLC="$(command -v glslc)"
    elif [ -n "${ANDROID_NDK_HOME:-}" ]; then
        GLSLC=$(find "$ANDROID_NDK_HOME/shader-tools" -name glslc -type f 2>/dev/null | head -1)
    fi
fi
if [ -z "$GLSLC" ] || [ ! -x "$GLSLC" ]; then
    echo "error: glslc not found. Set GLSLC=/path/to/glslc or ANDROID_NDK_HOME." >&2
    exit 1
fi

TMP_SPV="$(mktemp -t vk_postprocess.XXXXXX.spv)"
trap 'rm -f "$TMP_SPV"' EXIT

"$GLSLC" --target-env=vulkan1.0 -O -o "$TMP_SPV" "$SRC"

python3 - "$TMP_SPV" "$OUT_HEADER" "$SRC" <<'PYEOF'
import struct
import sys

spv_path, out_path, src_path = sys.argv[1], sys.argv[2], sys.argv[3]

with open(spv_path, "rb") as f:
    data = f.read()
if len(data) % 4 != 0:
    sys.exit(f"error: SPIR-V size {len(data)} is not a multiple of 4")

words = struct.unpack(f"<{len(data)//4}I", data)

with open(out_path, "w") as f:
    f.write("// Generated by scripts/build_vk_postprocess_shader.sh — do not edit by hand.\n")
    f.write(f"// Source: {src_path.split('client/')[-1] if 'client/' in src_path else src_path}\n")
    f.write("#pragma once\n\n")
    f.write("static const uint32_t vk_postprocess_spv[] = {\n")
    for i in range(0, len(words), 6):
        chunk = words[i:i+6]
        f.write("    " + ", ".join(f"0x{w:08x}u" for w in chunk) + ",\n")
    f.write("};\n\n")
    f.write("static const uint32_t vk_postprocess_spv_len = sizeof(vk_postprocess_spv);\n")
PYEOF

echo "wrote $OUT_HEADER ($(wc -c < "$TMP_SPV") bytes of SPIR-V)"
