package usbpass

import (
	"embed"
	"encoding/binary"
	"encoding/hex"
	"encoding/json"
	"sort"
	"strconv"
	"strings"
	"sync"
)

// Static models of Wacom tablets: the descriptors of the real device.
//
// Wacom's own drivers initialise the tablet from its complete report
// descriptor(s). An OS HID API does not hand a bridge that faithfully (Windows
// hid.dll returns a reconstructed, shorter descriptor and cannot read reports it
// dropped), so for the tablets known here the exported USB device is built from
// the captured descriptors instead, and only the live input reports come from
// the real tablet. To the importer's driver it is then indistinguishable from
// the tablet on a cable.
//
// Two sources:
//   - wacom_models/*.json: captured from hardware, including the real feature
//     report values (CTL-4100).
//   - wacom_db/descriptors.json: real report descriptors dumped from many tablets
//     (github.com/linuxwacom/wacom-hid-descriptors, regenerated by
//     tools/wacom_db). The drivers do not need the real values of the feature
//     reports (checked with the CTL-4100: all-zero features work), so those
//     are answered zero-filled at their declared size.

const wacomVendorID = 0x056A

//go:embed wacom_models/*.json
var wacomModelFS embed.FS

//go:embed wacom_db/descriptors.json
var wacomDBJSON []byte

// wacomIface is one HID interface of a tablet.
type wacomIface struct {
	Number     uint8
	ReportDesc []byte
	// Features holds the interface's feature reports (report id first); a nil value is
	// a report the real tablet answers with a STALL.
	Features map[uint8][]byte
	// inSizes is the size of each input report (report id excluded), from the descriptor.
	inSizes map[uint8]int
}

// wacomModel is a tablet, as its USB descriptors describe it.
type wacomModel struct {
	Name                          string
	VID, PID                      uint16
	DeviceDesc, ConfigDesc        []byte // ConfigDesc may be nil: built from the interfaces
	Manufacturer, Product, Serial string
	Ifaces                        []*wacomIface
}

type wacomIfaceFile struct {
	Number     uint8             `json:"number"`
	ReportDesc string            `json:"report_desc"`
	Features   map[string]string `json:"features"` // report id -> hex (report id first), or "ERRnn" when the tablet refuses it
}

type wacomModelFile struct {
	Name         string `json:"name"`
	VID          uint16 `json:"vid"`
	PID          uint16 `json:"pid"`
	DeviceDesc   string `json:"device_desc"`
	ConfigDesc   string `json:"config_desc"`
	Manufacturer string `json:"manufacturer"`
	Product      string `json:"product"`
	Serial       string `json:"serial"`
	// A single-interface tablet may give its interface inline.
	wacomIfaceFile
	Interfaces []wacomIfaceFile `json:"interfaces"`
}

func decodeWacomFeatures(in map[string]string) map[uint8][]byte {
	out := map[uint8][]byte{}
	for k, v := range in {
		id, err := strconv.ParseUint(k, 10, 8)
		if err != nil {
			continue
		}
		if strings.HasPrefix(v, "ERR") {
			out[uint8(id)] = nil
		} else if b, err := hex.DecodeString(v); err == nil && len(b) > 0 {
			out[uint8(id)] = b
		}
	}
	return out
}

func newWacomIface(number uint8, reportDesc []byte, features map[uint8][]byte) *wacomIface {
	in, _, feat := hidReportSizes(reportDesc)
	if features == nil {
		// No captured values: every declared feature report, zero-filled.
		features = map[uint8][]byte{}
		for id, n := range feat {
			features[id] = append([]byte{id}, make([]byte, n)...)
		}
	}
	return &wacomIface{Number: number, ReportDesc: reportDesc, Features: features, inSizes: in}
}

var (
	wacomModelsOnce sync.Once
	wacomModels     map[[2]uint16]*wacomModel
)

func loadWacomModels() {
	wacomModels = map[[2]uint16]*wacomModel{}
	ents, err := wacomModelFS.ReadDir("wacom_models")
	if err != nil {
		return
	}
	for _, e := range ents {
		raw, err := wacomModelFS.ReadFile("wacom_models/" + e.Name())
		if err != nil {
			continue
		}
		var f wacomModelFile
		if json.Unmarshal(raw, &f) != nil {
			continue
		}
		m := &wacomModel{
			Name: f.Name, VID: f.VID, PID: f.PID,
			Manufacturer: f.Manufacturer, Product: f.Product, Serial: f.Serial,
		}
		var e1, e2 error
		m.DeviceDesc, e1 = hex.DecodeString(f.DeviceDesc)
		m.ConfigDesc, e2 = hex.DecodeString(f.ConfigDesc)
		if e1 != nil || e2 != nil || len(m.DeviceDesc) != 18 {
			continue
		}
		ifs := f.Interfaces
		if f.ReportDesc != "" {
			ifs = append([]wacomIfaceFile{f.wacomIfaceFile}, ifs...)
		}
		for _, i := range ifs {
			rd, err := hex.DecodeString(i.ReportDesc)
			if err != nil || len(rd) == 0 {
				continue
			}
			m.Ifaces = append(m.Ifaces, newWacomIface(i.Number, rd, decodeWacomFeatures(i.Features)))
		}
		if len(m.Ifaces) > 0 {
			wacomModels[[2]uint16{f.VID, f.PID}] = m
		}
	}
}

// wacomModelFor returns the model captured from hardware, or nil if there is none.
func wacomModelFor(vid, pid uint16) *wacomModel {
	wacomModelsOnce.Do(loadWacomModels)
	return wacomModels[[2]uint16{vid, pid}]
}

type wacomDBEntry struct {
	Name       string `json:"name"`
	Interfaces []struct {
		Number     uint8  `json:"number"`
		ReportDesc string `json:"report_desc"`
	} `json:"interfaces"`
}

var (
	wacomDBOnce sync.Once
	wacomDB     map[uint16]wacomDBEntry
)

func loadWacomDB() {
	wacomDB = map[uint16]wacomDBEntry{}
	var raw map[string]wacomDBEntry
	if json.Unmarshal(wacomDBJSON, &raw) != nil {
		return
	}
	for k, v := range raw {
		if id, err := strconv.ParseUint(k, 16, 16); err == nil {
			wacomDB[uint16(id)] = v
		}
	}
}

// wacomDBHas reports whether the database knows the tablet.
func wacomDBHas(vid, pid uint16) bool {
	if vid != wacomVendorID {
		return false
	}
	wacomDBOnce.Do(loadWacomDB)
	_, ok := wacomDB[pid]
	return ok
}

// wacomKnown reports whether a tablet can be exported from a model.
func wacomKnown(vid, pid uint16) bool {
	return wacomModelFor(vid, pid) != nil || wacomDBHas(vid, pid)
}

// wacomModelFromDB builds a model for a tablet from its real report descriptors in
// the database. deviceDesc/configDesc are the device's own descriptors when the
// caller could read them (nil: synthesised); the strings and bcd come from the
// device. Feature reports are answered zero-filled at their declared size.
func wacomModelFromDB(vid, pid, bcd uint16, mfr, prod, serial string, deviceDesc, configDesc []byte) *wacomModel {
	if !wacomDBHas(vid, pid) {
		return nil
	}
	e := wacomDB[pid]
	m := &wacomModel{Name: e.Name, VID: vid, PID: pid, Manufacturer: mfr, Product: prod, Serial: serial}
	for _, i := range e.Interfaces {
		rd, err := hex.DecodeString(i.ReportDesc)
		if err != nil || len(rd) == 0 {
			return nil
		}
		m.Ifaces = append(m.Ifaces, newWacomIface(i.Number, rd, nil))
	}
	if len(m.Ifaces) == 0 {
		return nil
	}
	m.DeviceDesc = deviceDesc
	if len(m.DeviceDesc) != 18 {
		m.DeviceDesc = hidGenDeviceDesc(hidGenInfo{VID: vid, PID: pid, BCD: bcd, Manufacturer: mfr, Product: prod, Serial: serial})
	}
	m.ConfigDesc = patchHIDConfig(configDesc, m.Ifaces)
	return m
}

// patchHIDConfig adapts a configuration descriptor read from the device so each
// HID interface announces the model's report descriptor length. It returns nil
// (build one from the interfaces) if the device's own does not fit the model.
func patchHIDConfig(real []byte, ifs []*wacomIface) []byte {
	if len(real) < 25 || real[1] != 0x02 || int(real[2])|int(real[3])<<8 != len(real) {
		return nil
	}
	byNum := map[uint8]*wacomIface{}
	for _, f := range ifs {
		byNum[f.Number] = f
	}
	c := append([]byte(nil), real...)
	cur := -1
	patched := 0
	for i := 0; i+2 <= len(c) && c[i] != 0; i += int(c[i]) {
		switch c[i+1] {
		case 0x04:
			if i+9 <= len(c) {
				cur = int(c[i+2])
			}
		case 0x21:
			if f, ok := byNum[uint8(cur)]; ok && c[i] == 9 && i+9 <= len(c) {
				binary.LittleEndian.PutUint16(c[i+7:], uint16(len(f.ReportDesc)))
				patched++
			}
		}
	}
	if patched != len(ifs) {
		return nil
	}
	return c
}

func (f *wacomIface) maxInput() int {
	n := 0
	for id, sz := range f.inSizes {
		if id != 0 {
			sz++
		}
		n = max(n, sz)
	}
	return n
}

// buildHIDConfig makes a configuration for the model's HID interfaces, one
// interrupt-IN endpoint each (0x81, 0x82, ...).
func buildHIDConfig(ifs []*wacomIface) []byte {
	total := 9 + len(ifs)*25
	d := []byte{9, 0x02, byte(total), byte(total >> 8), byte(len(ifs)), 1, 0, 0x80, 250}
	for i, f := range ifs {
		mps := min(max(f.maxInput(), 8), hidGenMaxPacket)
		d = append(d,
			9, 0x04, f.Number, 0, 1, 0x03, 0, 0, 0,
			9, 0x21, 0x10, 0x01, 0, 1, 0x22, byte(len(f.ReportDesc)), byte(len(f.ReportDesc)>>8),
			7, 0x05, 0x81+byte(i), 0x03, byte(mps), byte(mps>>8), 1,
		)
	}
	return d
}

// wacomFeaturePort serves an interface's feature reports. A SET_REPORT is
// remembered (the driver switches modes that way and reads them back).
type wacomFeaturePort struct {
	mu   sync.Mutex
	vals map[uint8][]byte
}

func newWacomFeaturePort(f *wacomIface) *wacomFeaturePort {
	p := &wacomFeaturePort{vals: map[uint8][]byte{}}
	for id, v := range f.Features {
		p.vals[id] = append([]byte(nil), v...)
	}
	return p
}

func (p *wacomFeaturePort) idSets() (s [ppReportTypes]map[uint8]bool) {
	for i := range s {
		s[i] = map[uint8]bool{}
	}
	p.mu.Lock()
	defer p.mu.Unlock()
	for id := range p.vals {
		s[2][id] = true
	}
	return s
}

func (p *wacomFeaturePort) setReport(typ, id uint8, data []byte, hasReportIDs bool) error {
	if typ != 3 {
		return nil
	}
	p.mu.Lock()
	defer p.mu.Unlock()
	if len(p.vals[id]) > 0 && len(data) > 0 {
		v := append([]byte(nil), data...)
		if hasReportIDs && v[0] != id {
			v = append([]byte{id}, v...)
		}
		p.vals[id] = v
	}
	return nil
}

func (p *wacomFeaturePort) getReport(typ, id uint8, length int, _ bool) ([]byte, error) {
	if typ != 3 {
		return nil, errHIDNoInterfaces
	}
	p.mu.Lock()
	defer p.mu.Unlock()
	v := p.vals[id]
	if len(v) == 0 {
		return nil, errHIDNoInterfaces // the real tablet STALLs this one
	}
	if length < len(v) {
		v = v[:length]
	}
	return append([]byte(nil), v...), nil
}

// newWacomModelBackend builds the synthetic USB device for a model. Input
// reports of the real tablet are queued with pushReport.
func newWacomModelBackend(m *wacomModel) *hidGenBackend {
	var ifs []*hidGenIface
	for _, f := range m.Ifaces {
		hasIDs := false
		for id := range f.inSizes {
			hasIDs = hasIDs || id != 0
		}
		ifs = append(ifs, &hidGenIface{
			Number: f.Number, ReportDesc: f.ReportDesc, HasIDs: hasIDs,
			MaxInput: min(max(f.maxInput(), 1), hidGenMaxPacket),
			Ports:    []hidGenPort{newWacomFeaturePort(f)},
		})
	}
	b := newHIDGenBackend(hidGenInfo{
		VID: m.VID, PID: m.PID,
		Manufacturer: m.Manufacturer, Product: m.Product, Serial: m.Serial,
		Interfaces: ifs,
	})
	b.deviceDesc = append([]byte(nil), m.DeviceDesc...)
	if len(m.ConfigDesc) == 0 {
		b.configDesc = buildHIDConfig(m.Ifaces)
		return b
	}
	b.configDesc = append([]byte(nil), m.ConfigDesc...)
	// Serve each interface's input on the endpoint the descriptor names.
	cur := -1
	for i := 0; i+2 <= len(b.configDesc) && b.configDesc[i] != 0; i += int(b.configDesc[i]) {
		switch b.configDesc[i+1] {
		case 0x04:
			cur = int(b.configDesc[i+2])
		case 0x05:
			if i+7 <= len(b.configDesc) && b.configDesc[i+2]&0x80 != 0 {
				for _, f := range b.ifaces {
					if int(f.Number) == cur {
						f.ep = b.configDesc[i+2]
					}
				}
			}
		}
	}
	return b
}

// pushReport routes an input report of the real tablet, from any source, to the
// interface whose descriptor declares it, converted to the wire form. It returns
// false for a report to drop.
func (m *wacomModel) pushReport(b *hidGenBackend, rep []byte, srcIface int) bool {
	i, w := m.route(rep, srcIface)
	if w == nil {
		return false
	}
	b.push(i, w)
	return true
}

// route returns the interface index and the wire report for an input report
// from any source (hidraw and IOHID already give wire reports; under the Wacom
// Windows driver they arrive wrapped as vendor report 0xDC followed by the
// report, padded), or a nil report to drop. A report id several interfaces
// declare goes to the interface the source read it from (srcIface, -1 if it
// does not know), else to the first.
func (m *wacomModel) route(rep []byte, srcIface int) (int, []byte) {
	if len(rep) == 0 {
		return 0, nil
	}
	try := func(rep []byte) (int, []byte) {
		best := -1
		for i, f := range m.Ifaces {
			if n, ok := f.inSizes[rep[0]]; ok && rep[0] != 0 && len(rep) >= n+1 {
				if int(f.Number) == srcIface {
					best = i
					break
				}
				if best < 0 {
					best = i
				}
			}
		}
		if best < 0 {
			return 0, nil
		}
		n := m.Ifaces[best].inSizes[rep[0]]
		return best, append([]byte(nil), rep[:n+1]...)
	}
	if i, w := try(rep); w != nil {
		return i, w
	}
	if rep[0] == 0xDC && len(rep) > 1 {
		return try(rep[1:])
	}
	return 0, nil
}

// wireReport is route without the interface.
func (m *wacomModel) wireReport(rep []byte) []byte {
	_, w := m.route(rep, -1)
	return w
}

// applyWacomModel fills an ExportedDevice from a model and returns its backend.
func applyWacomModel(dev *ExportedDevice, m *wacomModel) *hidGenBackend {
	b := newWacomModelBackend(m)
	dev.Backend = b
	dev.DeviceDesc = b.deviceDesc
	dev.ConfigDesc = b.configDesc
	dev.Class, dev.SubClass, dev.Protocol = 0, 0, 0
	dev.ConfigVal, dev.NumConfigs = 1, 1
	dev.VID, dev.PID = m.VID, m.PID
	dev.BCDDevice = binary.LittleEndian.Uint16(m.DeviceDesc[12:14])
	dev.Interfaces = nil
	for range m.Ifaces {
		dev.Interfaces = append(dev.Interfaces, [3]uint8{0x03, 0x00, 0x00})
	}
	dev.Speed = 2
	return b
}

// hidReportSizes walks a report descriptor and returns, per report id, the size in
// bytes (id byte not included) of its input, output and feature reports.
func hidReportSizes(desc []byte) (in, out, feat map[uint8]int) {
	in, out, feat = map[uint8]int{}, map[uint8]int{}, map[uint8]int{}
	var id uint8
	var size, count int
	bits := [3]map[uint8]int{{}, {}, {}}
	type gstate struct {
		id          uint8
		size, count int
	}
	var stack []gstate
	for i := 0; i < len(desc); {
		b := desc[i]
		if b == 0xFE { // long item
			if i+1 >= len(desc) {
				break
			}
			i += 3 + int(desc[i+1])
			continue
		}
		n := [4]int{0, 1, 2, 4}[b&3]
		if i+1+n > len(desc) {
			break
		}
		var v int
		for k := 0; k < n; k++ {
			v |= int(desc[i+1+k]) << (8 * k)
		}
		i += 1 + n
		tag, typ := b>>4, (b>>2)&3
		switch typ {
		case 1: // global
			switch tag {
			case 0x7:
				size = v
			case 0x8:
				id = uint8(v)
			case 0x9:
				count = v
			case 0xA:
				stack = append(stack, gstate{id, size, count})
			case 0xB:
				if l := len(stack); l > 0 {
					id, size, count = stack[l-1].id, stack[l-1].size, stack[l-1].count
					stack = stack[:l-1]
				}
			}
		case 0: // main
			switch tag {
			case 0x8:
				bits[0][id] += size * count
			case 0x9:
				bits[1][id] += size * count
			case 0xB:
				bits[2][id] += size * count
			}
		}
	}
	for k, dst := range []map[uint8]int{in, out, feat} {
		for id, nb := range bits[k] {
			dst[id] = (nb + 7) / 8
		}
	}
	return in, out, feat
}

// wacomDBPIDs lists the tablets in the database.
func wacomDBPIDs() []uint16 {
	wacomDBOnce.Do(loadWacomDB)
	var out []uint16
	for p := range wacomDB {
		out = append(out, p)
	}
	sort.Slice(out, func(i, j int) bool { return out[i] < out[j] })
	return out
}
