import re

file_path = "/Users/amir/Projects/usbridge/usbridge_client/internal/service/h264_decoder.go"

with open(file_path, "r", encoding="utf-8") as f:
    content = f.read()

replacements = {
    "НАСТОЯЩИЙ декодер для H.264 с аппаратным ускорением": "REAL hardware-accelerated H.264 decoder",
    "Буферы для RTP пакетов": "Buffers for RTP packets",
    "SPS/PPS данные": "SPS/PPS data",
    "Состояние декодера": "Decoder state",
    "FFmpeg процесс для РЕАЛЬНОГО декодирования": "FFmpeg process for REAL decoding",
    "Мьютексы": "Mutexes",
    "фрагмент RTP пакета": "RTP packet fragment",
    "создает новый H.264 декодер с FFmpeg": "creates a new H.264 decoder with FFmpeg",
    "Запускаем FFmpeg процесс для РЕАЛЬНОГО декодирования H.264": "Start FFmpeg process for REAL H.264 decoding",
    "⚠️ FFmpeg недоступен, используем fallback: %v": "⚠️ FFmpeg unavailable, using fallback: %v",
    "✅ H.264 декодер с FFmpeg аппаратным ускорением инициализирован": "✅ H.264 decoder with FFmpeg hardware acceleration initialized",
    "устанавливает callback для обработки декодированных кадров": "sets a callback for processing decoded frames",
    "🔧 H264 декодер: callback установлен (callback != nil: %v)": "🔧 H264 decoder: callback set (callback != nil: %v)",
    "декодирует RTP пакет в изображение": "decodes an RTP packet into an image",
    "пустой RTP пакет": "empty RTP packet",
    "Логирование только первых 3 пакетов": "Logging only first 3 packets",
    "📦 H264 RTP пакет #%d: размер=%d байт": "📦 H264 RTP packet #%d: size=%d bytes",
    "Обрабатываем RTP пакет для получения NAL units": "Process RTP packet to get NAL units",
    "Если получили полные NAL units, декодируем их": "If complete NAL units are received, decode them",
    "Пакет обработан, но кадр еще не готов": "Packet processed, but frame is not ready yet",
    "устанавливает callback для декодированных кадров": "sets callback for decoded frames",
    "возвращает статистику декодера": "returns decoder statistics",
    "сбрасывает состояние декодера": "resets decoder state",
    "H.264 декодер сброшен": "H.264 decoder reset",
    "закрывает декодер и освобождает ресурсы": "closes decoder and frees resources",
    "🛑 H.264 декодер закрыт": "🛑 H.264 decoder closed",
    "обрабатывает RTP пакет и извлекает NAL units": "processes RTP packet and extracts NAL units",
    "пустой payload": "empty payload",
    "Полные NAL units (P, I, SPS, PPS)": "Complete NAL units (P, I, SPS, PPS)",
    "Неизвестный NAL тип: %d": "Unknown NAL type: %d",
    "обрабатывает фрагментированные NAL units (FU-A)": "processes fragmented NAL units (FU-A)",
    "слишком короткий FU-A пакет": "FU-A packet too short",
    "Начало нового фрагмента": "Start of a new fragment",
    "Начинаем с NAL заголовка": "Start with NAL header",
    "FU-A начало: NAL тип %d": "FU-A start: NAL type %d",
    "Продолжение фрагмента": "Fragment continuation",
    "Потерянный фрагмент, игнорируем": "Lost fragment, ignoring",
    "Конец фрагмента": "Fragment end",
    "Фрагмент не завершен": "Fragment incomplete",
    "обрабатывает агрегированные пакеты STAP-A": "processes aggregated STAP-A packets",
    "слишком короткий STAP-A пакет": "STAP-A packet too short",
    "Пропускаем STAP-A заголовок": "Skip STAP-A header",
    "Читаем размер NAL unit (2 байта)": "Read NAL unit size (2 bytes)",
    "Извлекаем NAL unit": "Extract NAL unit",
    "📦 STAP-A NAL unit: тип=%d, размер=%d": "📦 STAP-A NAL unit: type=%d, size=%d",
    "декодирует NAL units используя VDK": "decodes NAL units",
    "Обрабатываем SPS/PPS": "Process SPS/PPS",
    "Получен SPS": "SPS received",
    "Получен PPS": "PPS received",
    "Обрабатываем видео кадры": "Process video frames",
    "P-frame или I-frame": "P-frame or I-frame",
    "декодирует видео кадр используя FFmpeg РЕАЛЬНОГО декодирования": "decodes video frame using REAL FFmpeg decoding",
    "Если FFmpeg активен, отправляем данные туда для РЕАЛЬНОГО декодирования": "If FFmpeg is active, send data there for REAL decoding",
    "Создаем полный H.264 поток с start codes": "Create full H.264 stream with start codes",
    "Добавляем SPS/PPS если есть (нужно для всех кадров в начале потока)": "Add SPS/PPS if present (needed for all frames at the beginning of stream)",
    "Добавляем сам кадр": "Add the frame itself",
    "Отправляем данные в FFmpeg для РЕАЛЬНОГО декодирования": "Send data to FFmpeg for REAL decoding",
    "⚠️ Ошибка записи в FFmpeg: %v": "⚠️ Error writing to FFmpeg: %v",
    "Fallback на псевдо-декодирование": "Fallback to pseudo-decoding",
    "Минимальное логирование отправки кадров": "Minimal frame sending logging",
    "FFmpeg декодирует асинхронно через readFFmpegFrames()": "FFmpeg decodes asynchronously via readFFmpegFrames()",
    "Fallback если FFmpeg недоступен": "Fallback if FFmpeg unavailable",
    "FFmpeg недоступен, используем fallback декодирование": "FFmpeg unavailable, using fallback decoding",
    "🎬 Fallback декодирован %s #%d, размер NAL: %d байт": "🎬 Fallback decoded %s #%d, NAL size: %d bytes",
    "Создаем уменьшенное изображение для производительности": "Create downscaled image for performance",
    "создает быстрое изображение для fallback режима": "creates fast image for fallback mode",
    "Создаем МАЛЕНЬКОЕ изображение для производительности": "Create SMALL image for performance",
    "Быстрое заполнение на основе данных": "Fast filling based on data",
    "Пропускаем пиксели для скорости": "Skip pixels for speed",
    "Заполняем блок 4x4": "Fill 4x4 block",
    "Минимальная информация": "Minimal info",
    "создает изображение из H.264 данных": "creates image from H.264 data",
    "Создаем изображение 640x480 для лучшей производительности": "Create 640x480 image for better performance",
    "(реальный H.264 декодер покажет правильный размер)": "(real H.264 decoder will show correct size)",
    "Используем реальные H.264 данные для создания изображения": "Use real H.264 data to create image",
    "Создаем тестовый паттерн если нет данных": "Create test pattern if no data",
    "Добавляем информацию о кадре": "Add frame information",
    "ищет FFmpeg сначала локально, потом в PATH": "searches for FFmpeg first locally, then in PATH",
    "Получаем путь к исполняемому файлу": "Get executable path",
    "⚠️ Не удалось получить путь к исполняемому файлу: %v": "⚠️ Failed to get executable path: %v",
    "Проверяем FFmpeg в той же директории": "Check FFmpeg in the same directory",
    "Список возможных имен FFmpeg": "List of possible FFmpeg names",
    "🎯 Найден локальный FFmpeg: %s": "🎯 Local FFmpeg found: %s",
    "🔍 FFmpeg не найден в директории: %s": "🔍 FFmpeg not found in directory: %s",
    "Ищем в PATH": "Search in PATH",
    "🌐 Найден FFmpeg в PATH: %s": "🌐 FFmpeg found in PATH: %s",
    "❌ FFmpeg не найден ни локально, ни в PATH": "❌ FFmpeg not found locally or in PATH",
    "запускает FFmpeg процесс для РЕАЛЬНОГО декодирования": "starts FFmpeg process for REAL decoding",
    "Ищем FFmpeg - сначала локально, потом в PATH": "Search FFmpeg - first locally, then in PATH",
    "FFmpeg не найден ни локально, ни в PATH": "FFmpeg not found locally or in PATH",
    "🔍 Найден FFmpeg: %s": "🔍 FFmpeg found: %s",
    "FFmpeg команда для декодирования H.264 в реальном времени (упрощенная версия)": "FFmpeg command for real-time H.264 decoding (simplified version)",
    "Входной формат H.264": "Input format H.264",
    "Читаем из stdin": "Read from stdin",
    "Масштабируем до 640x480 для производительности": "Scale to 640x480 for performance",
    "Формат пикселей RGB": "Pixel format RGB",
    "Сырое видео на выход": "Raw video output",
    "Минимальные логи от FFmpeg": "Minimal logs from FFmpeg",
    "Выводим в stdout": "Output to stdout",
    "Создаем команду": "Create command",
    "Создаем pipe'ы ПЕРЕД запуском процесса": "Create pipes BEFORE starting process",
    "ошибка создания stdin pipe: %v": "error creating stdin pipe: %v",
    "ошибка создания stdout pipe: %v": "error creating stdout pipe: %v",
    "Запускаем FFmpeg процесс": "Start FFmpeg process",
    "Если первая попытка неудачна, пробуем без scale но с настройками низкой задержки": "If first attempt fails, try without scale but with low latency settings",
    "⚠️ Первая попытка неудачна, пробуем без масштабирования": "⚠️ First attempt failed, trying without scaling",
    "Принудительно задаем размер": "Force size",
    "ошибка создания stdin pipe для CPU: %v": "error creating stdin pipe for CPU: %v",
    "ошибка создания stdout pipe для CPU: %v": "error creating stdout pipe for CPU: %v",
    "ошибка запуска FFmpeg с CPU декодером: %v": "error starting FFmpeg with CPU decoder: %v",
    "Запускаем читатель кадров в отдельной горутине": "Start frame reader in separate goroutine",
    "🚀 FFmpeg процесс запущен для реального H.264 декодирования": "🚀 FFmpeg process started for real H.264 decoding",
    "читает декодированные кадры из FFmpeg": "reads decoded frames from FFmpeg",
    "🛑 Остановка чтения FFmpeg кадров": "🛑 Stopping FFmpeg frames reading",
    "🔄 Начало чтения кадров из FFmpeg...": "🔄 Starting to read frames from FFmpeg...",
    "RGB24 формат (640x480)": "RGB24 format (640x480)",
    "Читаем небольшими порциями": "Read in small chunks",
    "32KB за раз": "32KB at a time",
    "Логируем только первые 3 чтения": "Log only first 3 reads",
    "FFmpeg чтение #%d: %d байт": "FFmpeg read #%d: %d bytes",
    "⚠️ FFmpeg ошибка чтения #%d: %v": "⚠️ FFmpeg read error #%d: %v",
    "Проверяем, можем ли мы создать кадр из накопленных данных": "Check if we can create frame from accumulated data",
    "🎯 Пытаемся создать кадр из накопленных %d байт при ошибке": "🎯 Trying to create frame from accumulated %d bytes on error",
    "Добавляем прочитанные данные в буфер": "Add read data to buffer",
    "Проверяем, набрали ли мы достаточно данных для кадра": "Check if we have gathered enough data for frame",
    "Извлекаем один кадр": "Extract one frame",
    "Удаляем использованные данные": "Remove used data",
    "Создаем изображение": "Create image",
    "📊 Всего операций чтения: %d, всего байт: %d, декодировано кадров: %d": "📊 Total read operations: %d, total bytes: %d, decoded frames: %d",
    "пытается создать кадр из буфера данных": "tries to create frame from data buffer",
    "⚠️ Недостаточно данных для кадра: %d байт (ожидается %d)": "⚠️ Insufficient data for frame: %d bytes (expected %d)",
    "Конвертируем сырые RGB данные в image.Image": "Convert raw RGB data to image.Image",
    "Логируем только каждый 30й кадр для снижения нагрузки": "Log only every 30th frame to reduce load",
    "🎬 FFmpeg декодировал кадр #%d": "🎬 FFmpeg decoded frame #%d",
    "Отправляем кадр через callback": "Send frame via callback",
    "Логируем первые 10 кадров для отладки": "Log first 10 frames for debugging",
    "🔄 FFmpeg отправляет кадр #%d через callback": "🔄 FFmpeg sending frame #%d via callback",
    "Логируем только первые 5 раз чтобы не спамить": "Log only first 5 times to avoid spamming",
    "⚠️ Callback для кадров не установлен! Кадр #%d потерян": "⚠️ Callback for frames not set! Frame #%d lost",
    "конвертирует RGB данные в image.Image": "converts RGB data to image.Image",
    "останавливает FFmpeg процесс": "stops FFmpeg process",
    "рендерит H.264 данные в изображение": "renders H.264 data to image",
    "Создаем реалистичное изображение на основе H.264 данных": "Create realistic image based on H.264 data",
    "Используем несколько индексов для создания более качественного изображения": "Use multiple indices to create better quality image",
    "Для I-кадров (ключевых) делаем более контрастные цвета": "Make colors more contrast for I-frames (keyframes)",
    "Добавляем временную анимацию для демонстрации живого потока": "Add temporary animation to demonstrate live stream",
    "Добавляем блочную структуру характерную для H.264": "Add block structure typical for H.264",
    "создает тестовый паттерн": "creates test pattern",
    "Создаем цветные полосы для тестирования": "Create color stripes for testing",
    "Красный": "Red",
    "Зеленый": "Green",
    "Синий": "Blue",
    "Желтый": "Yellow",
    "Пурпурный": "Magenta",
    "Голубой": "Cyan",
    "Белый": "White",
    "Серый": "Gray",
    "Вспомогательные математические функции": "Auxiliary math functions",
    "Простая аппроксимация синуса": "Simple sine approximation",
    "рисует текст на изображении": "draws text on image",
    "рисует символ на изображении": "draws character on image",
    "Упрощенная реализация рисования символа": "Simplified character drawing implementation"
}

for k, v in replacements.items():
    content = content.replace(k, v)

with open(file_path, "w", encoding="utf-8") as f:
    f.write(content)

