//go:build windows

package hwid

import (
	"fmt"

	"golang.org/x/sys/windows/registry"
)

// rawMachineID on Windows reads HKLM\SOFTWARE\Microsoft\Cryptography\
// MachineGuid -- generated by Windows Setup and, per Microsoft's own docs,
// intended precisely as a machine identifier for exactly this kind of
// purpose (existing third-party licensing tools commonly read the same
// value). Stable across reboots, user profile changes, and application
// reinstalls; regenerated by a fresh Windows install or (per Microsoft's
// own sysprep documentation) a /generalize sysprep pass -- the latter is
// what OS-imaging/cloning tools are supposed to run precisely so cloned
// machines don't collide.
//
// Needs no elevation: this key is HKLM but readable by any authenticated
// user (only writable by admin), unlike some other machine-identity
// sources.
func rawMachineID() (id string, source string, err error) {
	k, err := registry.OpenKey(registry.LOCAL_MACHINE, `SOFTWARE\Microsoft\Cryptography`, registry.QUERY_VALUE|registry.WOW64_64KEY)
	if err != nil {
		return "", "", fmt.Errorf("open Cryptography registry key: %w", err)
	}
	defer k.Close()

	guid, _, err := k.GetStringValue("MachineGuid")
	if err != nil {
		return "", "", fmt.Errorf("read MachineGuid: %w", err)
	}
	return guid, "windows-machine-guid", nil
}
